language: r
r:
  - release
  - devel
  - bioc-release
  
r_github_packages:
  - jimhester/covr

r_check_args: "--as-cran"

bioc_required: true
bioc_use_devel: true
bioc-packages: BiocManager, zlibbioc

sudo: false
cran: http://cran.at.r-project.org

cache: packages

os:
- linux

after_success:
  - Rscript -e 'library(covr);codecov()'
  
notifications:
  email:
    on_success: change
    on_failure: always